articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    # path('<int:article_pk>/edit/', views.edit, name='edit'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', 
        views.comment_delete, 
        name='comment_delete'),
    # articles/5/comments/3/delete : 5번 글에 있는 댓글 3을 삭제 하자!
]

crud/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from imagekit.processors import ResizeToFill
from imagekit.models import ProcessedImageField, ImageSpecField

# Create your models here.
# 1. 모델(스키마) 정의
# 데이터베이스 테이블을 정의하고,
# 각각의 컬럼(필드) 정의
class Article(models.Model):
    # id : integer 자동으로 정의(Primary Key)
    # id = models.AutoField(primary_key=True) -> Integer 값이 자동으로 하나씩 증가(AUTOINCREMENT)
    # CharField - 필수인자로 max_length 지정
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = models.ImageField(blank=True)
    # ImageSpecield : Input 하나만 받고 잘라서 저장
    # ProcessedImageField : Input 받은 것을 잘라서 저장
    image_thumbnail = ImageSpecField(
        processors=[ResizeToFill(300, 300)],
        format = 'JPEG',
        options={'quality': 80}
    )
    # DateTimeField
    #    auto_now_add : 생성시 자동으로 저장
    #    auto_now : 수정시마다 자동으로 저장
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id} : {self.title}'

class Comment(models.Model):
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    # on_delete 
    # 1. CASCADE : 글이 삭제되었을 때 모든 댓글을 삭제
    # 2. PROTECT : 댓글이 존재하면 글 삭제 안됨.
    # 3. SET_NULL : 글이 삭제되면 NULL로 치환(NOT NULL일 경우 옵션 사용X)
    # 4. SET_DEFAULT : 디폴트 값으로 치환.

# models.py : python 클래스 정의
#           : 모델 설계도
# makemigrations : migration 파일 생성
#           : DB 설계도 작성
# migrate : migration 파일 DB 반영

articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('__all__')
        exclude = ('article', )



# class ArticleForm(forms.ModelForm):
#     class Meta:
#         model = Article
#         fields = '__all__'
        # fields = ('title')
        # exclude = ('title')
        # widgets = {
        #     'title': forms.TextInput(
        #         attrs={
        #             'placeholder': '제목을 입력바랍니다.'
        #         }
        #     )
        # }



# class ArticleForm(forms.Form):
#     title = forms.CharField(
#         max_length=1, 
#         label='제목',
#         widget=forms.TextInput(
#             attrs={
#                 'placeholder':'제목을 입력바랍니다.'
#             }
#         )
#     )
#     content = forms.CharField(
#         # label 내용 수정
#         label='내용',
#         # Django form 에서 HTML 속성 지정 -> widget
#         widget=forms.Textarea(
#             attrs={
#                 'class': 'my-content',
#                 'placeholder': '내용을 입력바랍니다.',
#                 'row': 5,
#                 'cols': 60,
#             }
#         )
#     )

articles/views.py
# from IPython import embed
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_GET

from .models import Article, Comment
from .forms import ArticleForm, CommentForm

# Create your views here.
@require_GET
def index(request):
    articles = Article.objects.order_by('-id')
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

# def new(request):
#     return render(request, 'articles/new.html')

def create(request):
    # 저장 로직
    if request.method == 'POST':
        # title = request.POST.get('title')
        # content = request.POST.get('content')
        article_form = ArticleForm(request.POST,request.FILES)
        # 검증
        if article_form.is_valid():
        # 검증에 성공하면 저장하고,
            # title = article_form.cleaned_data.get('title')
            # content = article_form.cleaned_data.get('content')
            # article = Article(title=title, content=content)
            article = article_form.save()
            return redirect('articles:detail', article.pk)
        #else:
            # 다시 폼으로 돌아가 -> 중복되서 제거!
    else:
    # GET 요청 -> Form
        article_form = ArticleForm()
    # GET -> 비어있는 Form context
    # POST -> 검증 실패시 에러메세지와 입력값 채워잔 Form context
    context = {
        'article_form': article_form
    }
    return render(request, 'articles/form.html',context)

def detail(request, article_pk):
    # article = Article.objects.get(pk=article_pk)
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.comment_set.all()
    comment_form = CommentForm()
    context = {
        'article': article,
        'comments': comments,
        'comment_form': comment_form
    }
    return render(request, 'articles/detail.html', context)

@require_POST
def delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    # if request.method == 'POST':
    article.delete()
    # messages.add_message(request, messages.INFO, '댓글이 삭제되었습니다.')
    messages.success(request, '댓글이 삭제되었습니다.')
    return redirect('articles:index')
    # else:
    #     return redirect('articles:detail', article.pk)

# def edit(request, article_pk):
#     article = Article.objects.get(pk=article_pk)
#     context = {
#         'article': article
#     }
#     return render(request, 'articles/edit.html', context)

def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        article_form = ArticleForm(request.POST, instance=article) #수정할때 instance 필요
        if article_form.is_valid():
            article = article_form.save()
            return redirect('articles:detail', article.pk)
    else:
        article_form = ArticleForm(instance=article)
    context = {
        'article_form': article_form
    }
    return render(request, 'articles/form.html', context)

@require_POST
def comment_create(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    # 1. modelform에 사용자 입력값 넣고
    comment_form = CommentForm(request.POST)
    # 2. 검증하고,
    if comment_form.is_valid():
    # 3. 맞으면 저장!
        # 3-1. 사용자 입력값으로 comment instance 생성 (저장은 X)
        comment = comment_form.save(commit=False)
        # 3-2. FK 넣고 저장
        comment.article = article
        comment.save()
    # 4. return redirect
    else:
        messages.success(request, '댓글이 형식이 맞지않습니다.')
    return redirect('articles:detail', article_pk)
    # comment = Comment()
    # comment.content = request.POST.get('comment_content')
    # comment.article = article
    # # comment.article_id = article_pk
    # comment.save()
    # return redirect('articles:detail', article_pk)

@require_POST
def comment_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    messages.success(request, '댓글이 삭제되었습니다.')
    return redirect('articles:detail', article_pk)

articles/templates/articles/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>게시판</title>
  <!--
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  {% block css %}{% endblock %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/articles/">게시판</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="nav-item active">
        <ul class="navbar-nav">
          <a class="nav-link" href="/articles/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/articles/new/">글 작성하기</a>
      </li>
      </ul>
    </div>
  </nav>
  <div class="container mt-5">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">
          {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
</body>

</html>

articles/templates/articles/create.html
{% extends 'articles/base.html' %}
{% block body %}
<h1>{{ article.id }}번째 글이 작성되었습니다.</h1>
{% endblock %}

articles/templates/articles/detail.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% block body %}
<h1>{{ article.id }}번 글</h1>
<h2>{{ article.title }}</h2>
<p>작성일자 : {{ article.created_at }}</p>
<p>수정일자 : {{ article.updated_at }}</p>
<hr>
<p>{{ article.content }}</p>
<img src="{{ article.image_thumbnail.url }}" alt="article.image_thumbnail.name"><br>
<!-- a tag : GET -->
<a href="{% url 'articles:index' %}">목록으로</a>
<form action="{% url 'articles:delete' article.pk %}" method="POST" 
onclick="return confirm('진짜 지울래?')">
    {% csrf_token %}
    <input type="submit" value="삭제">
</form>
<a href="{% url 'articles:update' article.pk %}">수정하기</a>
<hr>
<h3>댓글 작성 </h3>
<h4>댓글 수 : {{ comments.count }}</h4>

<form action="{% url 'articles:comment_create' article.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% for comment in comments %}
    <li>{{ comment.content }}</li>
    <li>{{ comment.created_at }}</li>
    <hr>
{% empty %}
    <p>댓글 작성 해주세요</p>
{% endfor %}

{% for comment in article.comment_set.all %}
    <li>{{ comment.content }}</li>
    <li>{{ comment.created_at }}</li>
    <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="POST" 
    onclick="return confirm('진짜 지울래?')">
        {% csrf_token %}
        <input type="submit" value="삭제">
    </form>
    <hr>
{% endfor %}

{% endblock %}

articles/templates/articles/edit.html
{% extends 'articles/base.html' %}

{% block body %}
<h1>글 수정하기</h1>
<form action="{% url 'articles:update' article.pk %}" method="POST">
  {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">제목</label>
    <input name="title" value="{{ article.title }}" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="제목을 입력하세요.">
    <small id="emailHelp" class="form-text text-muted">글의 제목을 작성 해주세요.</small>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">내용</label>
    <textarea name="content" class="form-control" id="exampleFormControlTextarea1" rows="3">{{ article.content }}</textarea>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<form action="" method = "POST">
  {%csrf_token%}
  {{ article_form.as_p}}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

articles/templates/articles/form.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% block body %}
{% if request.resolver_match.url_name == 'create' %}
<h1 class="text-center">글 작성하기</h1>
{% else %}
<h1 class="text-center">글 수정하기</h1>
{% endif %}

<form action="" method="POST" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form article_form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock %}

articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'articles/style.css' %}">
<style>
  tr > th:nth-of-type(2) {
    width: 50%;
  }
</style>
{% endblock %}
{% block body %}
  <img src="{% static 'articles/image.jpg' %}" alt="배경" width="200">
  <h1 class="text-center title">게시판에 오신걸 환영합니다.</h1>
  <a href="{% url 'articles:create' %}" class="btn btn-warning">글 작성하기</a>
  <table class="table mt-5">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">제목</th>
        <th scope="col">작성일자</th>
      </tr>
    </thead>
    <tbody>
      {% for article in articles %}
      <tr>
        <th scope="row">{{ article.id }}</th>
        <td>
          <a href="{% url 'articles:detail' article.pk %}">
              {{ article.title }}
          </a>
        </td>
        <td>{{ article.created_at }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

articles/templates/articles/new.html
{% extends 'articles/base.html' %}
{% block body %}
<h1 class="text-center">글 작성하기</h1>

<form action="" method="POST">
  {% csrf_token %}
  {{ article_form.as_p }}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

articles/templates/articles/new2.html
{% extends 'articles/base.html' %}
{% block body %}
<h1 class="text-center">글 작성하기</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ article_form.as_p }}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}